// <auto-generated />
using System;
using HealthPal.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HealthPal.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HealthPalDbContext))]
    partial class HealthPalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HealthPal.Domain.Entities.DailyHealthSummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double?>("ActiveCalories")
                        .HasColumnType("double precision")
                        .HasColumnName("active_calories");

                    b.Property<double?>("AverageHeartRate")
                        .HasColumnType("double precision")
                        .HasColumnName("average_heart_rate");

                    b.Property<string>("CoverageFlags")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("coverage_flags");

                    b.Property<int>("ExerciseCount")
                        .HasColumnType("integer")
                        .HasColumnName("exercise_count");

                    b.Property<int>("ExerciseDurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("exercise_duration_minutes");

                    b.Property<DateOnly>("LocalDate")
                        .HasColumnType("date")
                        .HasColumnName("local_date");

                    b.Property<double?>("MaxHeartRate")
                        .HasColumnType("double precision")
                        .HasColumnName("max_heart_rate");

                    b.Property<double?>("MinHeartRate")
                        .HasColumnType("double precision")
                        .HasColumnName("min_heart_rate");

                    b.Property<double?>("RestingHeartRate")
                        .HasColumnType("double precision")
                        .HasColumnName("resting_heart_rate");

                    b.Property<int?>("SleepMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("sleep_minutes");

                    b.Property<int?>("Steps")
                        .HasColumnType("integer")
                        .HasColumnName("steps");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("timezone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_daily_health_summaries");

                    b.HasIndex("UserId", "LocalDate")
                        .IsUnique()
                        .HasDatabaseName("ix_daily_health_summaries_user_id_local_date");

                    b.ToTable("daily_health_summaries", null, t =>
                        {
                            t.HasCheckConstraint("ck_daily_health_summaries_active_calories", "active_calories IS NULL OR active_calories >= 0");

                            t.HasCheckConstraint("ck_daily_health_summaries_exercise_count", "exercise_count >= 0");

                            t.HasCheckConstraint("ck_daily_health_summaries_exercise_duration", "exercise_duration_minutes >= 0");

                            t.HasCheckConstraint("ck_daily_health_summaries_sleep", "sleep_minutes IS NULL OR sleep_minutes >= 0");

                            t.HasCheckConstraint("ck_daily_health_summaries_steps", "steps IS NULL OR steps >= 0");
                        });
                });

            modelBuilder.Entity("HealthPal.Domain.Entities.Device", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("id");

                    b.Property<string>("AppVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("app_version");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("ModelVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("model_version");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("platform");

                    b.Property<string>("SourcePreference")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source_preference");

                    b.HasKey("UserId", "Id")
                        .HasName("pk_devices");

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("HealthPal.Domain.Entities.ExerciseSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double?>("Calories")
                        .HasColumnType("double precision")
                        .HasColumnName("calories");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<DateTime>("EndUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_utc");

                    b.Property<string>("ExternalRecordId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("external_record_id");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source_id");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("type");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<int>("ZoneOffsetMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("zone_offset_minutes");

                    b.HasKey("Id")
                        .HasName("pk_exercise_sessions");

                    b.HasIndex("UserId", "ExternalRecordId")
                        .IsUnique()
                        .HasDatabaseName("ix_exercise_sessions_user_id_external_record_id");

                    b.HasIndex("UserId", "StartUtc")
                        .HasDatabaseName("ix_exercise_sessions_user_id_start_utc");

                    b.ToTable("exercise_sessions", null, t =>
                        {
                            t.HasCheckConstraint("ck_exercise_sessions_calories", "calories IS NULL OR calories >= 0");

                            t.HasCheckConstraint("ck_exercise_sessions_duration", "duration_minutes >= 0");

                            t.HasCheckConstraint("ck_exercise_sessions_range", "end_utc >= start_utc");
                        });
                });

            modelBuilder.Entity("HealthPal.Domain.Entities.FatigueAssessment", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<double?>("BaseProbability")
                        .HasColumnType("double precision")
                        .HasColumnName("base_probability");

                    b.Property<double?>("CalibratedProbability")
                        .HasColumnType("double precision")
                        .HasColumnName("calibrated_probability");

                    b.Property<int>("CoverageHours")
                        .HasColumnType("integer")
                        .HasColumnName("coverage_hours");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("created_by");

                    b.Property<int?>("DataFreshnessMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("data_freshness_minutes");

                    b.Property<DateTime>("EvaluatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("evaluated_at_utc");

                    b.Property<string>("FeatureVectorHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("feature_vector_hash");

                    b.Property<string>("FeatureVectorJson")
                        .HasColumnType("text")
                        .HasColumnName("feature_vector_json");

                    b.Property<DateTime?>("LatestSampleAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("latest_sample_at_utc");

                    b.Property<DateOnly>("LocalDate")
                        .HasColumnType("date")
                        .HasColumnName("local_date");

                    b.Property<string>("MissingReasons")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("missing_reasons");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("model_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("status");

                    b.Property<double>("Threshold")
                        .HasColumnType("double precision")
                        .HasColumnName("threshold");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_fatigue_assessments");

                    b.HasIndex("UserId", "EvaluatedAtUtc", "ModelVersion")
                        .IsUnique()
                        .HasDatabaseName("ix_fatigue_assessments_user_id_evaluated_at_utc_model_version");

                    b.HasIndex("UserId", "LocalDate", "EvaluatedAtUtc")
                        .HasDatabaseName("ix_fatigue_assessments_user_id_local_date_evaluated_at_utc");

                    b.ToTable("fatigue_assessments", null, t =>
                        {
                            t.HasCheckConstraint("ck_fatigue_assessments_base_probability", "base_probability IS NULL OR (base_probability >= 0 AND base_probability <= 1)");

                            t.HasCheckConstraint("ck_fatigue_assessments_calibrated_probability", "calibrated_probability IS NULL OR (calibrated_probability >= 0 AND calibrated_probability <= 1)");

                            t.HasCheckConstraint("ck_fatigue_assessments_coverage_hours", "coverage_hours >= 0");

                            t.HasCheckConstraint("ck_fatigue_assessments_freshness", "data_freshness_minutes IS NULL OR data_freshness_minutes >= 0");

                            t.HasCheckConstraint("ck_fatigue_assessments_threshold", "threshold >= 0 AND threshold <= 1");
                        });
                });

            modelBuilder.Entity("HealthPal.Domain.Entities.HourlyHealthBin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double?>("ActiveCalories")
                        .HasColumnType("double precision")
                        .HasColumnName("active_calories");

                    b.Property<DateTime>("HourUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hour_utc");

                    b.Property<double?>("HrMax")
                        .HasColumnType("double precision")
                        .HasColumnName("hr_max");

                    b.Property<double?>("HrMean")
                        .HasColumnType("double precision")
                        .HasColumnName("hr_mean");

                    b.Property<double?>("HrMin")
                        .HasColumnType("double precision")
                        .HasColumnName("hr_min");

                    b.Property<int>("HrSampleCount")
                        .HasColumnType("integer")
                        .HasColumnName("hr_sample_count");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source_id");

                    b.Property<int?>("Steps")
                        .HasColumnType("integer")
                        .HasColumnName("steps");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<int>("ZoneOffsetMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("zone_offset_minutes");

                    b.HasKey("Id")
                        .HasName("pk_hourly_health_bins");

                    b.HasIndex("UserId", "HourUtc")
                        .HasDatabaseName("ix_hourly_health_bins_user_id_hour_utc");

                    b.HasIndex("UserId", "HourUtc", "SourceId")
                        .IsUnique()
                        .HasDatabaseName("ix_hourly_health_bins_user_id_hour_utc_source_id");

                    b.ToTable("hourly_health_bins", null, t =>
                        {
                            t.HasCheckConstraint("ck_hourly_health_bins_active_calories", "active_calories IS NULL OR active_calories >= 0");

                            t.HasCheckConstraint("ck_hourly_health_bins_hr_sample_count", "hr_sample_count >= 0");

                            t.HasCheckConstraint("ck_hourly_health_bins_steps", "steps IS NULL OR steps >= 0");
                        });
                });

            modelBuilder.Entity("HealthPal.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("device_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("replaced_by_token_hash");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId", "FamilyId")
                        .HasDatabaseName("ix_refresh_tokens_user_id_family_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("HealthPal.Domain.Entities.SyncBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("device_id");

                    b.Property<DateTime>("GeneratedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at_utc");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("payload_hash");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("result_json");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_sync_batches");

                    b.HasIndex("UserId", "DeviceId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_sync_batches_user_id_device_id_idempotency_key");

                    b.ToTable("sync_batches", (string)null);
                });

            modelBuilder.Entity("HealthPal.Domain.Entities.UserProfile", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DailyStepGoal")
                        .HasColumnType("integer")
                        .HasColumnName("daily_step_goal");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<bool>("ExperimentalFatigueConsent")
                        .HasColumnType("boolean")
                        .HasColumnName("experimental_fatigue_consent");

                    b.Property<string>("Gender")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("gender");

                    b.Property<string>("Goal")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("goal");

                    b.Property<double?>("HeightCm")
                        .HasColumnType("double precision")
                        .HasColumnName("height_cm");

                    b.Property<string>("PreferredSourceId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("preferred_source_id");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Timezone")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("timezone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<double?>("WeightKg")
                        .HasColumnType("double precision")
                        .HasColumnName("weight_kg");

                    b.HasKey("UserId")
                        .HasName("pk_user_profiles");

                    b.ToTable("user_profiles", null, t =>
                        {
                            t.HasCheckConstraint("ck_user_profiles_daily_step_goal", "daily_step_goal >= 100");

                            t.HasCheckConstraint("ck_user_profiles_height", "height_cm IS NULL OR (height_cm >= 50 AND height_cm <= 250)");

                            t.HasCheckConstraint("ck_user_profiles_weight", "weight_kg IS NULL OR (weight_kg >= 20 AND weight_kg <= 400)");
                        });
                });

            modelBuilder.Entity("HealthPal.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("RoleId")
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HealthPal.Domain.Entities.DailyHealthSummary", b =>
                {
                    b.HasOne("HealthPal.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_daily_health_summaries_asp_net_users_user_id");
                });

            modelBuilder.Entity("HealthPal.Domain.Entities.Device", b =>
                {
                    b.HasOne("HealthPal.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_devices_asp_net_users_user_id");
                });

            modelBuilder.Entity("HealthPal.Domain.Entities.ExerciseSession", b =>
                {
                    b.HasOne("HealthPal.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exercise_sessions_asp_net_users_user_id");
                });

            modelBuilder.Entity("HealthPal.Domain.Entities.FatigueAssessment", b =>
                {
                    b.HasOne("HealthPal.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fatigue_assessments_asp_net_users_user_id");
                });

            modelBuilder.Entity("HealthPal.Domain.Entities.HourlyHealthBin", b =>
                {
                    b.HasOne("HealthPal.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hourly_health_bins_asp_net_users_user_id");
                });

            modelBuilder.Entity("HealthPal.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("HealthPal.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("HealthPal.Domain.Entities.SyncBatch", b =>
                {
                    b.HasOne("HealthPal.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sync_batches_asp_net_users_user_id");
                });

            modelBuilder.Entity("HealthPal.Domain.Entities.UserProfile", b =>
                {
                    b.HasOne("HealthPal.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_profiles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("HealthPal.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("HealthPal.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("HealthPal.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("HealthPal.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
